
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author achuu
 */
public class cv_w extends javax.swing.JFrame {

    static void pass(String p1) {
        String x=p1; //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form vw
     */
    public cv_w() {
        initComponents();
        String filePath = "C:\\Users\\achuu\\Documents\\NetBeansProjects\\inventory\\inventory.txt";
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)cvwjTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(";");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(cv_w.this, "Error","Error", JOptionPane.ERROR_MESSAGE); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cvwjTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<-");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Raleway", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available weapons");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        cvwjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "model no", "model name", "type", "magazine", "damage", "accuracy", "availability", "price"
            }
        ));
        cvwjTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvwjTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cvwjTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 700, 290));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Buy");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 270, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        customer.main(new String[] {});         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cvwjTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvwjTable1MouseClicked
        
    }//GEN-LAST:event_cvwjTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 int i = cvwjTable1.getSelectedRow();

  DefaultTableModel model = (DefaultTableModel) cvwjTable1.getModel();
  if((i>=0)){
      String p1=JOptionPane.showInputDialog(this,"Enter user name");
      String p2=JOptionPane.showInputDialog(this,"Enter no of pieces");
   int c=Integer.parseInt(p2);
   int b=Integer.parseInt((String) model.getValueAt(i, 6));
              int d=b-c;
              
          if(search.searchcust(p1)){
              if((d>=0)){
              
      model.setValueAt(d,i,6);
      String y=(String) model.getValueAt(i, 1);
      
          
      
      
            try{
                String filepath5 = "C:\\Users\\achuu\\Documents\\NetBeansProjects\\inventory\\inventory.txt";
                File file5 = new File(filepath5);
                FileWriter fw5 = new FileWriter(file5);
                BufferedWriter bw5 = new BufferedWriter(fw5);
                
                for(int a = 0; a < cvwjTable1.getRowCount(); a++){
                    for(int b2 = 0; b2<cvwjTable1.getColumnCount(); b2++){
                        bw5.write(cvwjTable1.getValueAt(a,b2).toString()+";");
                    }
                    bw5.newLine();
                } 
            
                
                
                bw5.close();
                fw5.close();
            
                write(p1,y,c);
                JOptionPane.showMessageDialog(null,"Successfully bought");
                
                
            }
            catch(Exception e){
                
                JOptionPane.showMessageDialog(cv_w.this, "Error","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
  else
            JOptionPane.showMessageDialog(cv_w.this, "Weapon shortage","Error", JOptionPane.ERROR_MESSAGE);// TODO add your handling code here:
          }
          else
              JOptionPane.showMessageDialog(cv_w.this, "Invalid entry","Error", JOptionPane.ERROR_MESSAGE);
          
  }
   else
            JOptionPane.showMessageDialog(cv_w.this, "Error,Select a row","Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    void write(String x,String y,int z){
    try{
BufferedWriter writer6 = new BufferedWriter(
                                new FileWriter("C:\\Users\\achuu\\Documents\\NetBeansProjects\\inventory\\log.txt", true));


writer6.write(x);
writer6.write(System.getProperty("path.separator"));
writer6.write(y);
writer6.write(System.getProperty("path.separator"));
writer6.write(new Integer(z).toString());
writer6.write(System.getProperty("path.separator"));
writer6.newLine();
writer6.close();


}catch(Exception e){
   JOptionPane.showMessageDialog(rootPane,"Error"); 
} 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cv_w().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cvwjTable1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
